### ISSUE TITLE
Neither AsmHelper nor Compiling provides the additional directories specified by //css_searchdir

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#44]
Hi Oleg,

There is one thing of #26 remaining, and I came to the conclusion that's because neither AsmHelper nor Compiling provides the additional directories specified by //css_searchdir. Here's the situation:

My test script 'RefTest.cs' references a library 'RefRedir.dll' using //css_reference. Now, that 'RefRedir.dll' references another assembly located in a different folder. Of course this cannot work, how shall .NET find that folder when loading the assemblies. To fix this, I have added the assembly's folder to the top-level 'RefTest.cs' script, using //css_searchdir, assuming that either AsmHelper or Compiling would detect the additional directories. But it seems that neither does, or at least doesn't provide this information.

I am pretty sure that either AsmHelper or Compiling actually parses the //css_searchdir directive. Could you pass that information to either AsmHelper.ProbingDirs or CompilingInfo? Thanks.

Best regards,
Matthias

**Comment by oleg-shilo** [comment]
>I am pretty sure that either AsmHelper or Compiling actually parses the //css_searchdir directive.

Not exactly. 

`AsmHelper` is CS-Script neutral. It is an independent utility class, which is responsible (as name suggests) for assisting when working with assemblies. It has nothing to do with CS-Script except it is bundled with it in the same assembly. And today, when better assembly loading/invocation solutions are available (e.g. `dynamic`), it's relevance is diminishing. And because `AsmHelper` never deals with the scripts it never parses any of them. 

`CSScript.Compile(*)` indeed parses the script but because it is not involved in the assembly loading it has nothing to do with neither CS-Script `AsmHelper` nor .NET `AppDomain` thus it cannot possibly pass the knowledge about the probing dirs to anywhere. And in fact it shouldn't as some users use it specifically for compiling scripts, without further loading.

CS-Script provides a handy parser that can extract your probing dirs. Thus you can easily set either `AppDomain` or `AsmHelper` up to resolve not found assemblies. If your wish you can even create your extensions to do the task in a single step:

```C#
string asm = CSSCript.Compile(script);
var asm_helper = new AsmHelper(asm).SetProbingDirsFromFile(script);
asm_helper.Invoke(...
...
static class Extensions
{
    public static AsmHelper SetProbingDirsFromCode(this AsmHelper helper, string code)
    {
        var parser = new csscript.CSharpParser(code, isFile: false);
        helper.ProbingDirs = parser.ExtraSearchDirs;
        return helper;
    }

    public static AsmHelper SetProbingDirsFromFile(this AsmHelper helper, string file)
    {
        var parser = new csscript.CSharpParser(file, isFile: true);
        helper.ProbingDirs = parser.ExtraSearchDirs;
        return helper;
    }
}
```

**Comment by maettu-this** [comment]
I also assumed that rather `CSSCript.Compile` than `AsmHelper` actually parses the script. So could compiling provide the additional directories as e.g. `csscript.CompilingInfo.Input.ExtraSearchDirs` or similar? I just distaste to parse the script again, since `CSSCript.Compile` already does so...

**Comment by oleg-shilo** [comment]
The search dirs are kind of a lesser importance. They only serve the role of an assistant for finding the assemblies, which are the actual reason for search dirs to exist. And the assemblies are already captured in the `Input` so it's possible to rediscover the assemblies dirs back from the Input:
```C#
var dirs = CSScript.CompilingHistory
                   .Last().Value
                   .Input.ReferencedAssemblies
                   .Cast<string>()
                   .Select(x=>Path.GetDirectoryName(x))
                   .Distinct();
```
It's even possible to preserve in the `CompilingInfo` the whole CS-Script context - `ScriptParser`. And I actually like the idea as it allows preserving information about all compiled files and `//css_` directives. 

Though I am not entirely sure about putting such a rich object in the history collection without having any purging mechanism.

**Comment by maettu-this** [comment]
Unfortunately, in the case I initially described, the assemblies are not captured in the `Input`, as they are indirectly referenced, so it's not possible to rediscover them. That's when `//css_searchdir` came into play.

I agree that it's maybe not a good idea to put the whole object in the history. But I think `CompilingInfo` should at least contain the information captured by the `//css_...` directives.

**Comment by oleg-shilo** [comment]
OK, you convinced me. The latest commit delivers the following changes.
- Added `CompilingInfo.ParsingContext` that contains all parsing result data without resorting to store the whole parser.
- Added `CSScript.LastCompilingResult`. It is always set to the `CompilingInfo` of the last compile operation as opposite to the `CSScript.CompilingHistory`, which is kept only if enabled. 
Useful when no concurrency is expected. 
- Added SimpleAsmProbing for simple assembly probing within specified dirs. Supports `using` statement declaration.

```C#
var script = CSScript.Load("printer.cs");

var search_dirs = CSScript.LastCompilingResult.ParsingContext.SearchDirs;

using (SimpleAsmProbing.For(search_dirs))
{
    dynamic printer = script.CreateObject("Printer");
    printer.Print("Hello World!");
}
```
Will be available in the next release.

**Comment by maettu-this** [comment]
Excellent! I only need the `CSScript.LastCompilingResult` indeed. And yesterday on my way home something similar crossed my mind:

How about having a `CompilingHistoryMode` instead of a single `CSScript.KeepCompilingHistory` enabled/disabled, something like:
```
[Flags]
enum CompilingHistoryMode
{
	Disabled = 0,
	Enabled = 1,
	LastCompilation = 2,
	LastXCompilations = 4, // where X is e.g. 10 or 20 or whatever seems a useful value
	AllCompilations = 8,
	CompactInfo = 16,
	FullInfo = 32,

	// Combinations
	LastCompilationFullInfo = Enabled | LastCompilation | FullInfo,
	AllCompilationsCompactInfo = Enabled | AllCompilations | CompactInfo,
}
```
It's then up to the user to configure the amount of data kept. Alternatively, the three items could be three separate enabled/disable flags, i.e. `CSScript.KeepCompilingHistory` + `CSScript.IncludeAllCompilationsInCompilingHistory` + `CSScript.IncludeFullInfoInCompilingHistory` are similar. Just some ideas, though I think with your above described implementation most of this is already covered.

**Comment by oleg-shilo** [comment]
Sorry, but I don't think such an intensive configurability is justified in this case. 

`CSScript.LastCompilingResult` was actually always implemented and I only had to expose it via public API. Thus I almost do not consider it as a change but rather refactoring.  As for the `CompilingHistory`, reimplementing it in the way you suggest require effort that would significantly outweigh the benefit.

I know it's not what you were hoping for but I for now the functionality as follows:

- `CSScript.LastCompilingResult` is always available for the last compilation
- `CSScript.CompilingHistory` is populated only if it's enabled via `CSScript.KeepCompilingHistory`. User is responsible for the history purging. 

If your proposal gains the community support then further improvements may be considered.

**Comment by oleg-shilo** [comment]
Done. Please find the enhancement in the release v3.24.0

**Comment by maettu-this** [comment]
Hi Oleg, I have just upgraded to 3.24.0 and I think something went wrong:

With 3.22.0, compilation works as expected, all required assemblies can be resolved. But with 3.24.0, `CSScript.CompileFile()` throws:
```
csscript.CompilerException was caught
  Message="(0,0): error CS0006: Metadata file 'System.Linq' could not be found\r\n"
  Source="CSScriptLibrary"
  ErrorCount=1
  StackTrace:
       bei csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
       bei csscript.CSExecutor.Compile(String scriptFileName)
       bei csscript.CSExecutor.Compile(String scriptFile, String assemblyFile, Boolean debugBuild)
       bei CSScriptLibrary.CSScript.CompileWithConfig(String scriptFile, String assemblyFile, Boolean debugBuild, Settings scriptSettings, String compilerOptions, String[] refAssemblies)
       bei CSScriptLibrary.CSScript.CompileFile(String scriptFile, String assemblyFile, Boolean debugBuild, String[] refAssemblies)
       bei _MyHostingApplication_.CompileScript(AsmHelper& helper, String& assemblyFilePath) in _MyWorkspace_\ScriptRun.cs:
  InnerException: 
```
It looks as if assembly resolving for compilation no longer works correctly.

Note that the state of `CSScript` before calling `CompileFile()` is as follows:

- `AssemblyResolvingEnabled = true`
- `CacheEnabled = false`
- `CompilingHistory.Count = 0`
- `EvalNamespaces` is set to using System | using System.IO | using System.Diagnostics | using System.Collections.Generic | using System.Threading
- `KeepCompilingHistory = false`
- Algorithms are both kept at defaults
- `ScriptCache = {CSScriptLibrary.CSScript.LoadedScript[0]}`
- `ShareHostRefAssemblies = true`

Interestingly, this applies to 3.22.0 as well as 3.24.0.

By the way, I've been wondering why some of the releases are versioned x.y.z.0 (e.g. "v3.24.0.0") whereas others just x.y.z (e.g. "v3.22.0"). Is there any reason for this?

**Comment by oleg-shilo** [comment]
I cannot be sure what is happening there as it's not clear what code you are executing. 

I am guessing that your code is using some of the Linq namespace members. Most likely you can address this by adding references to System.Linq.dll by any of the referencing techniques: manually from hosting code, from script itself, with global DefaualtRefAssemblies, via EvalNamespaces...

&gt; why some of the releases are versioned x.y.z.0 (e.g. "v3.24.0.0") whereas others just x.y.z (e.g. "v3.22.0"). Is there any reason for this?
No the releases are not versioned this way. :) It is only a title in the release notes. The assembly and file versions have always been (and still are) 4-units version.

**Comment by maettu-this** [comment]
I've just tried again, `CSScript.GlobalSettings.EnableDbgPrint = false;` doesn't help unfortunately, I still get `(0,0): error CS0006: Metadata file 'System.Linq' could not be found`. It actually happens with any of my scripts used for testing, and none of them uses Linq.

What I am doing in my hosting application is pretty simple:
`effectiveAssemblyFilePath = CSScript.CompileFile(this.scriptFilePath, intendedAssemblyFilePath, true);`
That's it. Using .NET 3.5. v3.24.0 throws, v3.22.0 works fine.

**Comment by maettu-this** [comment]
I guess this new issue is not directly related to this #44, I just came across it while verifying #44. Let me know if I should better create a new issue.

**Comment by oleg-shilo** [comment]
> I guess this new issue is not directly related to this #44,

I think so. There is no need for a new issue. This one is fine.
 
Can you please share your `this.scriptFilePath` content or its equivalent. I just cannot reproduce the error with my scripts. I am not sure that the trigger is in your script but to eliminate it completely I want to ensure that we are running the same tests.

The following code just out of box in a fresh VS project with `cs-script` NuGet package triggers no error whatsoever:

```C#
var code = @"using System;
             public class Script
             {
                 public int Sum(int a, int b)
                 {
                     return a+b;
                 }
             }";

var script = "script.cs";
File.WriteAllText(script, code);

var asm = CSScript.CompileFile(script);
```

**Comment by maettu-this** [comment]
Well, looks a tricky one to catch... My script is equally simple, just:
```
public static class Script
{
	internal const int ExpectedResult = 0;

	public static int Main()
	{
		return (ExpectedResult);
	}
}
```
In order to support finding the root cause of this issue, I could extend/modify my hosting application's solution such it doesn't refer to `CSScriptLibrary.dll` directly but rather the `\Source\CSScriptLibrary` source code. Maybe I can find the root cause, but it may take a bit.

In the meantime some thoughts that have crossed my mind:

- Could the issue be cause by some .NET 4+ -vs- 3.5 mismatch? I am still using 3.5... In the end, when all other assemblies can be found, why not that one too.
-  The message is "...Metadata file 'System.Linq' could not be found..." but that namespace is actually located in the `System.Core` assembly. And [CS0006](https://msdn.microsoft.com/en-us/library/a92dycyz.aspx) states "...the .dll was not found...", so somehow the wrong name ?!?

**Comment by maettu-this** [comment]
I have just found (e.g. "System.Core; System.Linq;") in the documentation of `CSScript.AggregateReferencedAssemblies`. Maybe there indeed is a confusing among assemblies (.dll files) and namespaces.

**Comment by oleg-shilo** [comment]
Excellent. Thank you. 

Yes MS started moving System.Linq namespace around assemblies: 
- On .NET 3.5 LINQ types are implemented in System.Core.dll. 
- On .NET 4+ in both `System.Core.dll` and `System.Linq.dll`.
- On .NET Core it is only System.Linq.dll

Will need to make `CSScript.AggregateReferencedAssemblies` a target specific.

Shouldn't take long.

**Comment by oleg-shilo** [comment]
had a look at code and it actually does consider target runtime:
```C#
#if net4
            if (Utils.IsLinux())
            {
                return "System;System.Core;";
            }
            else
            {
                if (Utils.IsNet45Plus())
                    return "System.Core; System.Linq;";
                else
                    return "System.Core;";
            }
#else
```
Will need to digg more...

**Comment by oleg-shilo** [comment]
OK. Found it. It is triggered by the latest DbgPrint feature. It doe add ref assemblies though in this case it failed to verify at runtime if adding `System.Linq;` is compatible with the runtime.
Fixed in db5141c8bec5ed558ea191a664dee2a73102eb07.

Will make a hot fix release tomorrow or so.

**Comment by maettu-this** [comment]
Excellent. I have just tried to extend my solution with CSScript source code references but failed:
It's no good idea to try putting CSScript source code into a .NET 3.5 / VS2008 solution ;-)

Looking forward for the fixed version. Take your time, no need to hurry from my side.

**Comment by oleg-shilo** [comment]
Just before publishing the release I wanted to ask you to test the fix in your environment. 

I have added a .NET 3.5 build for early testing here: https://github.com/oleg-shilo/cs-script/blob/master/Source/Build/CSScriptLibrary.v3.5.dll.

It does work in my environment for Target_3.5 VS project but considering how tricky this defect was I would like an independent confirmation.

Thank you

**Comment by maettu-this** [comment]
Almost there ;-)

The issue with `System.Linq` has gone, thumbs up!

Returning to the initial request:

- Additional dirs specified by `//css_searchdir` now make it into `CSScript.LastCompilingResult.ParsingContext.SearchDirs`, thumbs up as well.
- But I have found out the very same issue applies to assemblies specified by a relative path with the `//css_reference` directive:
   - As we've already concluded, `AsmHelper.ProbingDirs` cannot know about such paths.
   - However, `CSScript.LastCompilingResult.ParsingContext.ReferencedAssemblies` is fully aware of the assemblies referenced by `//css_reference`, but these paths don't make it into the `CSScript.LastCompilingResult.ParsingContext.SearchDirs`.

So, additionally adding the paths of `ReferencedAssemblies` to `SearchDirs`, and I think that will be the final thumbs up!

**Comment by oleg-shilo** [comment]
We need to remember `CSScript.LastCompilingResult.ParsingContext` is all about the script execution context associated with a given script only. This class is not responsible for locating the assemblies but only for extracting and aggregating the information required for further locating/probing effort. 

Probing is done by both CLR and internal `AssemblyResolver`. The complete final set of referenced assemblies with their absolute paths is pushed to the actual C# compiler as part of `CompilerParameters` input argument. This argument is preserved into  `CSScript.LastCompilingResult.Input'. 

Thus you can access it like this:
```C#
string[] actual_asms = CSScript.LastCompilingResult.Input
                                                   .ReferencedAssemblies
                                                   .Cast<string>()
                                                   .ToArray();
```

**Comment by maettu-this** [comment]
OK, got it. I thought that `ParsingContext.SearchDirs` will contain the aggregated search directories, not just the additional, but of course that was a false-assumption since it is just the 'ParsingContext' as the name already states. The input is dealt with in 'Input'.

I guess I got confused because `ParsingContext` also has `ReferencedAssemblies` and `ReferencedResources` properties.

I have adapted my code as follows:
```
helper = new AsmHelper(assemblyFilePath, "ScriptDomain", false);
DebugPaths(helper.ProbingDirs, "Initial probing directories of the AsmHelper:");

var assemblyDirs = PathEx.DistinctDirectories(CSScript.LastCompilingResult.Input.ReferencedAssemblies);
DebugPaths(assemblyDirs, "Resolved referenced assembly directories (specified by //css_reference):");

var resourceDirs = PathEx.DistinctDirectories(CSScript.LastCompilingResult.Input.LinkedResources);
DebugPaths(resourceDirs, "Resolved referenced resource directories (specified by //css_resource):");

var additionalDirs = PathEx.Distinct(CSScript.LastCompilingResult.ParsingContext.SearchDirs);
DebugPaths(additionalDirs, "Additional search directories (specified by //css_searchdir):");

helper.ProbingDirs = PathEx.Distinct(helper.ProbingDirs, assemblyDirs, resourceDirs, additionalDirs).ToArray();
DebugPaths(helper.ProbingDirs, "Aggregated probing directories for the AsmHelper:");
```
Works now :-) Thumbs up on that as well. Thanks a lot!

**Comment by oleg-shilo** [comment]
>I guess I got confused because ParsingContext also has ReferencedAssemblies and ReferencedResources properties.

Yeah, I know what you mean. My thought was "these are the assemblies referenced by names, absolute or relative path as they found and extracted from the script code during parsing". I kind of do not see any better name, while agree that it's not ideal. I was just afraid that any attempt to improve naming would only create more confusion.

Anyway, I am glad we can tick this one. Will let it settle for a couple days and if no further bug reports will do the release.

Thank you for helping with the investigative part, otherwise it would be very difficult to find the cause of that "System.Linq" problem.

**Comment by maettu-this** [comment]
Based on our discussions in #50, I now use `LastCompilingResult` successfully as follows:
```
	var helper = new AsmHelper(assemblyFilePath, "ScriptDomain", false);
	DebugPaths(helper.ProbingDirs, "Initial probing directories of the AsmHelper:");

	if (CSScript.LastCompilingResult != null)
	{
		var compilingDirs = AggregateCompilingDirs(CSScript.LastCompilingResult);
		helper.ProbingDirs = PathEx.Distinct(helper.ProbingDirs, compilingDirs).ToArray();
		DebugPaths(helper.ProbingDirs, "Aggregated probing directories for the AsmHelper:");
	}

```
Where:
```
static IEnumerable<string> AggregateCompilingDirs(csscript.CompilingInfo compilingResult)
{
	if (compilingResult.Input != null)
	{
		if (compilingResult.Input.ReferencedAssemblies != null)
		{
			var assemblyDirs = PathEx.DistinctDirectories(CSScript.LastCompilingResult.Input.ReferencedAssemblies);
			DebugPaths(assemblyDirs, "Resolved referenced assembly directories (specified by //css_reference):");

			foreach (var dir in assemblyDirs)
				yield return(dir);
		}

		if (compilingResult.Input.LinkedResources != null)
		{
			var resourceDirs = PathEx.DistinctDirectories(CSScript.LastCompilingResult.Input.LinkedResources);
			DebugPaths(resourceDirs, "Resolved referenced resource directories (specified by //css_resource):");

			foreach (var dir in resourceDirs)
				yield return (dir);
		}
	}

	if (compilingResult.ParsingContext != null)
	{
		var additionalDirs = PathEx.Distinct(CSScript.LastCompilingResult.ParsingContext.SearchDirs);
		DebugPaths(additionalDirs, "Additional search directories (specified by //css_searchdir):");

		foreach (var dir in additionalDirs)
			yield return (dir);
	}
}
```
So `LastCompilingResult` does provide the information that I have requested with this issue. The issue may be closed. Or it may be kept open until the potential improvement (provide the information as an out argument of `CompileFile()` and/or `CompileWithOptions()` as suggested in #50) has either been implemented or definitely rejected.
Based on the finding in #50 / #56, I think an out argument would better prevent potential concurrency issues, the `Compile...()` method(s) would provide the `Result` in an atomic manner.

**Comment by oleg-shilo** [comment]
Just to be noted that `CompileFile()` has overload that returns compiling context as an `out` parameter.
